### ISSUE TITLE
bot is not working

### ISSUE THREAD

**Issue by askfriends** [bipinkrish/IPTV-Bot#1]
bot is throwing error so will u fix it?

**Comment by bipinkrish** [comment]
What error!

**Comment by askfriends** [comment]
> What error!

some module not found error i dont rember as i deketed the repo. check urself if u dont find any i will try again and show u exact error

**Comment by bipinkrish** [comment]
Do you think i didn't tested it? Please open the issue with all details

**Comment by askfriends** [comment]
> Do you think i didn't tested it? Please open the issue with all details

here is the error 
`Total Channels: 31477
Total Streams: 7021
Traceback (most recent call last):
  File "c:\Users\j\Documents\IPTV-Bot\main.py", line 79, in <module>
    app.run()
  File "C:\Users\ji\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyrogram\methods\utilities\run.py", line 84, in run
    self.start()
  File "C:\Users\j\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\j\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
  File "C:\Users\j\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Users\j\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyrogram\client.py", line 576, in load_session
    raise AttributeError("The API key is required for new authorizations. "
AttributeError: The API key is required for new authorizations. More info: https://docs.pyrogram.org/start/auth`

**Comment by bipinkrish** [comment]
You are not setting all variables correctly, please follow the rules of environmental values

**Comment by askfriends** [comment]
> You are not setting all variables correctly, please follow the rules of environmental values

bro im putting correct values as i am running few more bots so i am well aware of these envs, here is SS
![boterror](https://user-images.githubusercontent.com/2517219/235082500-bf3cf386-ce82-40f6-89cd-c3cc58ada34f.png)

**Comment by bipinkrish** [comment]
Use config file

**Comment by askfriends** [comment]
> Use config file

yeah its working now and thanks.
btw i have a suggestion:
set a default timer after which the msg gets deleted automatically or after clicking on any channel button, that msg gets deleted automatically.

And if i find any working channel from elsewhere, can i add that channel in the list?

**Comment by bipinkrish** [comment]
You need to provide that to IPTV resources
